config/routes.rb
MyBook::Application.routes.draw do
  resources :status_updates

  resources :users

  

end

app/models/status_update.rb
class StatusUpdate < ActiveRecord::Base
	attr_accessible :content
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :avatar, :profilePic, :name, :education, :hobbies, :birthday, :relationship
	has_many :status_updates
	mount_uploader :profilePic, ProfilePicUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  before_action :set_status_update, only: [:show, :edit, :update, :destroy]

  # GET /status_updates
  # GET /status_updates.json
  def index
    @users = User.all
    @status_updates = StatusUpdate.all
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
  end

  # GET /status_updates/new
  def new
    @status_update = StatusUpdate.new
  end

  # GET /status_updates/1/edit
  def edit
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(status_update_params)

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to @status_update, notice: 'Status update was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status_update }
      else
        format.html { render action: 'new' }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_updates/1
  # PATCH/PUT /status_updates/1.json
  def update
    respond_to do |format|
      if @status_update.update(status_update_params)
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_update
      @status_update = StatusUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_update_params
      params.require(:status_update).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @status = StatusUpdate.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :education, :hobbies, :birthday, :relationship, :profilePic, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/status_updates/_form.html.erb
<%= form_for(@status_update) do |f| %>
  <% if @status_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_update.errors.count, "error") %> prohibited this status_update from being saved:</h2>

      <ul>
      <% @status_update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing status_update</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html - Copy.erb
<h1>Listing status_updates</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @status_updates.each do |status_update| %>
      <tr>
        <td><%= status_update.content %></td>
        <td><%= status_update.user_id %></td>
        <td><%= link_to 'Show', status_update %></td>
        <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
        <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status update', new_status_update_path %>

app/views/status_updates/index.html.erb
<h1>Listing status_updates</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @status_updates.each do |status_update| %>
      <tr>
        <td><%= status_update.content %></td>
        <td><%= status_update.user_id %></td>
        <td><%= link_to 'Show', status_update %></td>
        <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
        <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status update', new_status_update_path %>


<%= link_to 'New User', new_user_path %>

app/views/status_updates/new.html.erb
<h1>New status_update</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @status_update.content %>
</p>


<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :hobbies %><br>
    <%= f.text_field :hobbies %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %> 
  </div>
  <div class="field">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship %>
  </div>
  <div class="field">
    <%= f.label :avatar %> (URL of image)<br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html - Copy.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Education</th>
      <th>Hobbies</th>
      <th>Birthday</th>
      <th>Relationship</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.education %></td>
        <td><%= user.hobbies %></td>
        <td><%= user.birthday %></td>
        <td><%= user.relationship %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.html.erb
<h1>Name : <%= @users.first.name %></h1>

<br>
<%= image_tag @users.first.avatar %>
<br>

<p>Education : <%= @users.first.education %></p>
<br>
<p>Hobbies : <%= @users.first.hobbies %></p>
<br>
<p>Birthday : <%= @users.first.birthday %></p>
<br>
<p>Relationship : <%= @users.first.relationship %></p>

<br>
<%= link_to 'Edit', edit_user_path(@users.first) %>
<br><br>

<h1>Status </h1>

<% @status.each do |status_update| %>
  <%= status_update.content %>
  <%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %>
  <br>
  <hr>
<% end %>
<br><br>
<%= link_to 'New Status update', new_status_update_path %>
<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>ProfilePic</strong>
  <%= image_tag @user.avatar %>
</p>

<p>
  <strong>Education:</strong>
  <%= @user.education %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @user.hobbies %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @user.relationship %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>